import { Link } from "wouter";
import { ArrowRight, BadgeCheck, Bath, ChevronDown, Clock3, Droplets, Flame, House, MapPin, Phone, ShieldCheck, Sparkles, Wrench, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { mainServices, MAPS_URL, PHONE_DISPLAY, PHONE_TEL } from "../App";

const services = [
  {title:"Everyday plumbing repairs", text:"Fixtures, valves, connections, and the issues that interrupt a normal day.", icon:Wrench, href:"/plumbing-repair-fairfield"},
  {title:"Drains & sewer lines", text:"From a slow sink to a recurring backup, get help understanding the pattern.", icon:Droplets, href:"/drain-cleaning-fairfield"},
  {title:"Water heaters", text:"Repair or installation guidance for a more reliable hot-water routine.", icon:Flame, href:"/water-heater-repair-fairfield"},
  {title:"Leaks & urgent issues", text:"Call when water is active, spreading, or needs a prompt next step.", icon:Zap, href:"/emergency-plumber-fairfield"},
  {title:"Home plumbing", text:"Residential plumbing support designed around your home and your schedule.", icon:House, href:"/residential-plumbing-fairfield"},
  {title:"Gas line plumbing", text:"Safety-first conversations for gas-line and appliance plumbing needs.", icon:ShieldCheck, href:"/gas-line-plumbing-fairfield"},
];

const faqs = [
  ["What areas does A2Z Plumbing serve?", "A2Z Plumbing is based in Fairfield and also serves nearby Suisun City. Call to confirm availability for your address."],
  ["What should I do if water is actively leaking?", "If it is safe, turn off the nearest fixture valve or the main water supply, move belongings away from the water, and call directly."],
  ["Can you help with both small and larger plumbing issues?", "Yes. Customers call about everyday fixture repairs, drains, leaks, water heaters, and larger system questions such as repiping."],
  ["How do I reach A2Z Plumbing?", "Call +1 510-701-2472. A direct conversation helps us understand what is happening and the most useful next step."],
];

export default function Home(){
 return <div className="home"><section className="hero"><div className="hero-watermark">A2Z</div><div className="container hero-grid"><div className="hero-content"><div className="eyebrow"><span className="eyebrow-dot"/> FAIRFIELD’S LOCAL PLUMBING TEAM</div><h1>Plumbing that keeps your day <em>moving.</em></h1><p className="hero-copy">Thoughtful, responsive plumbing service for homes and businesses in Fairfield and nearby Suisun City.</p><div className="hero-actions"><Button asChild className="btn-copper"><a href={PHONE_TEL}><Phone size={17}/> Call Now</a></Button><a className="text-link light-link" href="#services">Explore services <ArrowRight size={16}/></a></div><div className="hero-proof"><span><ShieldCheck size={18}/> Clear communication</span><span><Clock3 size={18}/> Open 24 hours</span></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=1400&q=85" alt="Professional plumber working under a sink"/><div className="hero-card"><span className="hero-card-icon"><Sparkles size={19}/></span><div><b>Need a plumber?</b><span>Let’s talk through it.</span></div><a href={PHONE_TEL}><ArrowRight size={18}/></a></div></div></div><div className="hero-bottom"><div className="container hero-bottom-inner"><span>Plumbing repairs</span><i/> <span>Water heaters</span><i/> <span>Drain cleaning</span><i/> <span>Emergency help</span></div></div></section>
 <section className="intro-section"><div className="container intro-grid"><div className="intro-number">01 <span>ABOUT A2Z</span></div><div><div className="eyebrow dark-eyebrow">THE PRACTICAL DIFFERENCE</div><h2>Good plumbing service starts with a useful conversation.</h2></div><div className="intro-copy"><p>When something goes wrong at home, you want a plumber who listens, explains what may be happening, and helps you decide on the next step. That is the experience A2Z Plumbing LLC is building in Fairfield.</p><a className="text-link" href="#why-us">Why homeowners call A2Z <ArrowRight size={16}/></a></div></div></section>
 <section id="services" className="services-section"><div className="container"><div className="section-heading"><div><div className="eyebrow dark-eyebrow">WHAT WE HANDLE</div><h2>From the everyday to the unexpected.</h2></div><p>Plumbing is personal. We keep the details clear and the work focused on the problem in front of you.</p></div><div className="service-grid">{services.map(({title,text,icon:Icon,href})=><Link href={href} className="service-card" key={title}><span className="icon-box"><Icon size={20}/></span><h3>{title}</h3><p>{text}</p><span className="card-link">{title} <ArrowRight size={15}/></span></Link>)}</div></div></section>
 <section className="feature-band"><div className="container feature-grid"><div className="feature-image"><img src="https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=85" alt="Plumbing tools and repair work"/><div className="feature-stamp"><BadgeCheck size={18}/><span>Local<br/><b>service</b></span></div></div><div className="feature-copy"><div className="eyebrow">WHEN IT MATTERS</div><h2>Fast answers for the moments you’d rather not have.</h2><p>A leak under the sink. A drain that will not clear. A water heater that goes cold. You do not need more confusion—you need a calm place to start.</p><div className="feature-list"><span><span className="check">✓</span> Direct phone support</span><span><span className="check">✓</span> Straightforward next steps</span><span><span className="check">✓</span> Respect for your home</span></div><Button asChild className="btn-copper"><a href={PHONE_TEL}>Speak with a plumber <Phone size={16}/></a></Button></div></div></section>
 <section id="why-us" className="why-section"><div className="container"><div className="why-heading"><div className="eyebrow dark-eyebrow">WHY A2Z</div><h2>Professional without the runaround.</h2></div><div className="why-grid"><div className="why-item"><span>01</span><h3>Listen first</h3><p>We start with your description of the problem and the context around it.</p></div><div className="why-item"><span>02</span><h3>Explain clearly</h3><p>We keep the conversation practical, so you can make an informed decision.</p></div><div className="why-item"><span>03</span><h3>Respect the space</h3><p>Thoughtful work includes care for your home, your time, and your routine.</p></div><div className="why-item"><span>04</span><h3>Stay reachable</h3><p>Call directly when something changes or you need help deciding what is urgent.</p></div></div></div></section>
 <section id="service-areas" className="areas-section"><div className="container areas-grid"><div><div className="eyebrow dark-eyebrow">SERVICE AREAS</div><h2>Close to home in Solano County.</h2><p>A2Z Plumbing is based in Fairfield and also serves nearby Suisun City. If you are not sure whether your address is in range, call and ask.</p><div className="area-links"><Link href="/plumber-fairfield"><MapPin size={17}/> Plumber in Fairfield <ArrowRight size={15}/></Link><Link href="/plumber-suisun-city"><MapPin size={17}/> Plumber in Suisun City <ArrowRight size={15}/></Link></div></div><div className="map-frame"><iframe title="A2Z Plumbing LLC location map" src="https://www.google.com/maps?q=A2Z+Plumbing+LLC,+4970+Paramount+Ct,+Fairfield,+CA+94534&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><a className="map-overlay" href={MAPS_URL} target="_blank" rel="noreferrer"><MapPin size={16}/> View Google Maps listing <ArrowRight size={15}/></a></div></div></section>
 <section className="reviews-section"><div className="container"><div className="section-heading review-heading"><div><div className="eyebrow dark-eyebrow">CUSTOMER FEEDBACK</div><h2>Service people remember.</h2></div><div className="review-score"><strong>5.0</strong><span>Google listing rating<br/><small>4 public reviews</small></span></div></div><div className="review-grid"><blockquote><div className="stars">★★★★★</div><p>“Professional, courteous, and respectful of our home.”</p><cite>— Recent Google reviewer</cite></blockquote><blockquote><div className="stars">★★★★★</div><p>“Fast service and excellent workmanship when we needed help.”</p><cite>— Recent Google reviewer</cite></blockquote><blockquote><div className="stars">★★★★★</div><p>“Quick, efficient, reasonably priced, and professional.”</p><cite>— Recent Google reviewer</cite></blockquote></div></div></section>
 <section id="faqs" className="faq-section"><div className="container faq-grid"><div><div className="eyebrow dark-eyebrow">QUESTIONS, ANSWERED</div><h2>Before you pick up the phone.</h2><p>Not sure if your issue needs a plumber yet? Start here, then call when you are ready.</p><Button asChild className="btn-navy"><a href={PHONE_TEL}>Call {PHONE_DISPLAY} <Phone size={16}/></a></Button></div><div className="faq-stack">{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></div></section>
 <section className="final-cta"><div className="container final-cta-inner"><div><div className="eyebrow">READY WHEN YOU ARE</div><h2>Let’s get your plumbing moving in the right direction.</h2></div><Button asChild className="btn-copper"><a href={PHONE_TEL}><Phone size={17}/> Call {PHONE_DISPLAY}</a></Button></div></section></div>
}
